# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  database: Ugif
  username: root
  host: 127.0.0.1
  port: 3306
  pool: 5
  timeout: 5000

development:
  adapter: mysql2
  encoding: utf8
  database: Ugif
  username: root
  host: 127.0.0.1
  port: 3306

test:
  <<: *default
  database: testing_db
  adapter: mysql2
  encoding: utf8
  username: root
  host: 127.0.0.1
  port: 3306
